### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [bkaradzic/go-lz4#18]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for go-lz4 and versioning would help Debian keep up with development.

**Comment by bkaradzic** [comment]
Is there preferable way to version it?

Is this ok?

    1.0.49

Where 49 comes from `git rev-list --count HEAD`.

**Comment by aviau** [comment]
It would be great if you used semver: http://semver.org/

**Comment by bkaradzic** [comment]
Added https://github.com/bkaradzic/go-lz4/tree/v1.0.0

**Comment by aviau** [comment]
thanks!
